spring:
  data:
    rest.basePath: /auction-example/projections
    mongodb:
      uri: mongodb://mongo:27017
      database: auction_example
  jpa:
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

#kafka:
#  stream:
#    schema-registry-url: http://schema_registry:8081
#    application-id: example_auction
#    application-server: localhost:1234
#    kafka-properties:
#      application-id: account-events-consumer-app
#      client-id: account-events-consumer-client
#      bootstrap-servers: broker:9092
#    projection-properties:
#      state-store: /tmp/kafka-streams/
#      partition-count: 10
#      replication-factor: 1
#      config:
#        retention.ms: 86400000
